from __future__ import annotations
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 22 12:41:22 2026

@author: ines
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot cBAG associations with harmonized cognitive domain composites.

Inputs
------
1) Per-cohort brain-age validation tables:
   $BASE/results/BrainAgePrediction<COHORT>_stratified_groupcv_targetnorm_bagbiascorr_oofglobal/
       ablation_<FEATURE_SET>/validation_figures/subject_level_validation_input.csv

2) Harmonized cognitive composite outputs generated by:
   build_harmonized_cognitive_composites_v3_recalculate_addecode.py

   $BASE/results/composite_cognition/<COHORT>_cognitive_composites.csv

Outputs
-------
$BASE/results/composite_cognition/cbag_domain_associations/

For each feature set:
  - Figure_CognitiveDomains_<feature_set>_raw.png/pdf
  - Figure_CognitiveDomains_<feature_set>_resid.png/pdf
  - cbag_cognitive_domain_stats.csv
  - cbag_cognitive_domain_merge_report.csv
  - merged CSVs for audit

Figure layout
-------------
Rows = cohorts: ADNI, ADRC, HABS, AD_DECODE
Columns = domains:
  Memory_Composite
  Executive_Function_Composite
  Processing_Speed_Composite
  Language_Composite
  Visuospatial_Composite

Each panel shows cBAG versus the selected domain composite with Pearson r, p-value, n,
and a simple linear regression line.
"""



import argparse
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats


COHORTS = ["ADNI", "ADRC", "HABS", "AD_DECODE"]
FEATURE_SETS = [
    "imaging_only",
    "imaging_demographics",
    "imaging_biomarkers",
    "full",
    "full_no_cardiovascular",
]

RESULTS_DIR_MAP = {
    "ADNI": "BrainAgePredictionADNI_stratified_groupcv_targetnorm_bagbiascorr_oofglobal",
    "ADRC": "BrainAgePredictionADRC_stratified_groupcv_targetnorm_bagbiascorr_oofglobal",
    "HABS": "BrainAgePredictionHABS_stratified_groupcv_targetnorm_bagbiascorr_oofglobal",
    "AD_DECODE": "BrainAgePredictionADDECODE_stratified_groupcv_targetnorm_bagbiascorr_oofglobal",
}

CBAG_PRIORITY = [
    "cBAG_oof_global_raw_clean",
    "cBAG_oof_global",
    "cBAG_bias_corrected",
    "cBAG_BiasCorrected",
    "cBAG",
    "BAG_bias_corrected",
    "BrainAgeGap_bias_corrected",
    "BrainAgeGap",
    "BAG",
]

DOMAINS_RAW = [
    "Memory_Composite",
    "Executive_Function_Composite",
    "Processing_Speed_Composite",
    "Language_Composite",
    "Visuospatial_Composite",
]
DOMAINS_RESID = [f"{d}_resid" for d in DOMAINS_RAW]

DOMAIN_LABELS = {
    "Memory_Composite": "Memory",
    "Executive_Function_Composite": "Executive function",
    "Processing_Speed_Composite": "Processing speed",
    "Language_Composite": "Language",
    "Visuospatial_Composite": "Visuospatial",
    "Memory_Composite_resid": "Memory residual",
    "Executive_Function_Composite_resid": "Executive function residual",
    "Processing_Speed_Composite_resid": "Processing speed residual",
    "Language_Composite_resid": "Language residual",
    "Visuospatial_Composite_resid": "Visuospatial residual",
}


# ---------------------------------------------------------------------
# Arguments and paths
# ---------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    default_work = os.environ.get("WORK", "/mnt/newStor/paros/paros_WORK")
    default_base = Path(default_work) / "ines"

    parser = argparse.ArgumentParser(
        description="Plot cBAG against harmonized cognitive domain composites."
    )
    parser.add_argument("--base-dir", default=str(default_base), help="Base project dir, default $WORK/ines")
    parser.add_argument("--results-root", default=None, help="Default: <base-dir>/results")
    parser.add_argument("--composite-dir", default=None, help="Default: <base-dir>/results/composite_cognition")
    parser.add_argument("--outdir", default=None, help="Default: <composite-dir>/cbag_domain_associations")
    parser.add_argument("--feature-sets", nargs="+", default=FEATURE_SETS, help="Feature sets to plot")
    parser.add_argument("--cohorts", nargs="+", default=COHORTS, help="Cohorts to plot")
    parser.add_argument("--min-n", type=int, default=10, help="Minimum complete cases per panel")
    parser.add_argument("--formats", nargs="+", default=["png", "pdf"], help="Output formats")
    return parser.parse_args()


def validation_csv_path(results_root: Path, cohort: str, feature_set: str) -> Path:
    return (
        results_root
        / RESULTS_DIR_MAP[cohort]
        / f"ablation_{feature_set}"
        / "validation_figures"
        / "subject_level_validation_input.csv"
    )


def composite_csv_path(composite_dir: Path, cohort: str) -> Path:
    return composite_dir / f"{cohort}_cognitive_composites.csv"


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------
def safe_numeric(s: pd.Series) -> pd.Series:
    return pd.to_numeric(s, errors="coerce")


def first_existing(df: pd.DataFrame, candidates: Sequence[str]) -> Optional[str]:
    for c in candidates:
        if c in df.columns:
            return c
    lower_map = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if str(c).lower() in lower_map:
            return lower_map[str(c).lower()]
    return None


def norm_key(x) -> Optional[str]:
    """Normalize subject/session keys for cross-file merges."""
    if pd.isna(x):
        return None
    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return None

    s = re.sub(r"\.csv$", "", s)
    s = re.sub(r"_conn_plain$", "", s)
    s = re.sub(r"_master_T_?\d*$", "", s)
    s = re.sub(r"_temp_T_?\d*$", "", s)
    s = re.sub(r"^(R\d+)(y\d+)$", r"\1_\2", s)

    return s


def rid_from_any(x) -> Optional[str]:
    """Extract ADNI RID-like number from Rxxxx_y*, PTID, or plain numeric ID."""
    if pd.isna(x):
        return None
    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return None

    m = re.search(r"R(\d+)", s)
    if m:
        return str(int(m.group(1)))

    m = re.search(r"_S_(\d+)", s)
    if m:
        return str(int(m.group(1)))

    if re.fullmatch(r"\d+(\.0)?", s):
        return str(int(float(s)))

    return None


def adni_y_from_key(x) -> Optional[str]:
    if pd.isna(x):
        return None
    s = str(x)
    m = re.search(r"_y(\d+)", s, flags=re.IGNORECASE)
    if m:
        return f"y{m.group(1)}"
    return None


def possible_merge_keys(df: pd.DataFrame) -> List[str]:
    keys = []
    tokens = [
        "connectome", "subject", "participant", "match", "regional",
        "id", "rid", "ptid", "visit", "viscode", "runno", "med_id", "exam",
    ]
    for c in df.columns:
        low = str(c).lower()
        if any(t in low for t in tokens):
            keys.append(c)
    return keys


def choose_best_merge(
    val: pd.DataFrame,
    comp: pd.DataFrame,
    cohort: str,
) -> Tuple[pd.DataFrame, Dict[str, object]]:
    """Merge validation table with cognitive composites using best overlap.

    For ADNI, prefer RID+visit when possible. For other cohorts, exact normalized key is usually enough.
    """
    val = val.copy()
    comp = comp.copy()

    report = {
        "cohort": cohort,
        "merge_strategy": "none",
        "validation_key": "",
        "composite_key": "",
        "overlap": 0,
        "n_validation_rows": len(val),
        "n_composite_rows": len(comp),
        "merged_rows": 0,
    }

    val_keys = possible_merge_keys(val)
    comp_keys = possible_merge_keys(comp)

    # ------------------------------------------------------------------
    # ADNI special: validation keys often look like R4028_y4, whereas
    # metadata/composite may contain RID plus VISCODE/VISCODE2.
    # ------------------------------------------------------------------
    if cohort == "ADNI":
        val_key_candidates = [k for k in ["connectome_key", "subject_id", "connectome_full_key"] if k in val.columns]
        if not val_key_candidates:
            val_key_candidates = val_keys

        comp_rid_col = first_existing(comp, ["RID", "rid"])
        comp_visit_col = first_existing(comp, ["VISCODE", "VISCODE2", "visit", "Visit", "EXAMDATE"])

        if comp_rid_col is not None:
            for vk in val_key_candidates:
                val["_merge_rid"] = val[vk].map(rid_from_any)
                val["_merge_visit"] = val[vk].map(adni_y_from_key)
                comp["_merge_rid"] = comp[comp_rid_col].map(rid_from_any)

                if comp_visit_col is not None:
                    comp["_merge_visit"] = comp[comp_visit_col].astype(str).str.strip().str.lower()
                    # Normalize common ADNI visits: bl -> y0, m48 -> y4, m24 -> y2, etc.
                    visit_map = {
                        "bl": "y0", "baseline": "y0", "sc": "y0",
                        "m00": "y0", "m0": "y0", "0": "y0", "0.0": "y0",
                        "m12": "y1", "12": "y1", "12.0": "y1",
                        "m24": "y2", "24": "y2", "24.0": "y2",
                        "m36": "y3", "36": "y3", "36.0": "y3",
                        "m48": "y4", "48": "y4", "48.0": "y4",
                    }
                    comp["_merge_visit"] = comp["_merge_visit"].replace(visit_map)

                    overlap_pair = len(
                        set(zip(val["_merge_rid"], val["_merge_visit"])).intersection(
                            set(zip(comp["_merge_rid"], comp["_merge_visit"]))
                        )
                    )
                    if overlap_pair > 0:
                        comp_small = comp.sort_values(comp.columns.tolist()[0]).drop_duplicates(["_merge_rid", "_merge_visit"], keep="first")
                        merged = val.merge(comp_small, on=["_merge_rid", "_merge_visit"], how="left", suffixes=("", "_cog"))
                        report.update({
                            "merge_strategy": "ADNI_RID_visit",
                            "validation_key": vk,
                            "composite_key": f"{comp_rid_col}+{comp_visit_col}",
                            "overlap": overlap_pair,
                            "merged_rows": len(merged),
                        })
                        return merged, report

                # RID-only fallback
                overlap_rid = len(set(val["_merge_rid"].dropna()).intersection(set(comp["_merge_rid"].dropna())))
                if overlap_rid > report["overlap"]:
                    comp_small = comp.sort_index().drop_duplicates("_merge_rid", keep="first")
                    merged = val.merge(comp_small, on="_merge_rid", how="left", suffixes=("", "_cog"))
                    report.update({
                        "merge_strategy": "ADNI_RID_only",
                        "validation_key": vk,
                        "composite_key": comp_rid_col,
                        "overlap": overlap_rid,
                        "merged_rows": len(merged),
                    })
                    if overlap_rid > 0:
                        return merged, report

    # ------------------------------------------------------------------
    # General exact normalized key matching.
    # ------------------------------------------------------------------
    best = None
    for vk in val_keys:
        vnorm = val[vk].map(norm_key)
        vset = set(vnorm.dropna().astype(str))
        if not vset:
            continue
        for ck in comp_keys:
            cnorm = comp[ck].map(norm_key)
            cset = set(cnorm.dropna().astype(str))
            overlap = len(vset.intersection(cset))
            if best is None or overlap > best[0]:
                best = (overlap, vk, ck)

    if best is not None and best[0] > 0:
        overlap, vk, ck = best
        val["_merge_key"] = val[vk].map(norm_key)
        comp["_merge_key"] = comp[ck].map(norm_key)
        comp_small = comp.sort_index().drop_duplicates("_merge_key", keep="first")
        merged = val.merge(comp_small, on="_merge_key", how="left", suffixes=("", "_cog"))
        report.update({
            "merge_strategy": "normalized_exact",
            "validation_key": vk,
            "composite_key": ck,
            "overlap": overlap,
            "merged_rows": len(merged),
        })
        return merged, report

    # ------------------------------------------------------------------
    # Last resort: if row counts are identical, align by row order.
    # This should rarely be used; it is documented in the merge report.
    # ------------------------------------------------------------------
    if len(val) == len(comp):
        domain_cols = [c for c in comp.columns if c in DOMAINS_RAW + DOMAINS_RESID or c.endswith("_n_components") or c.endswith("_n_domains")]
        merged = val.copy()
        for c in domain_cols:
            merged[c] = comp[c].values
        report.update({
            "merge_strategy": "row_order_fallback",
            "validation_key": "row_index",
            "composite_key": "row_index",
            "overlap": len(val),
            "merged_rows": len(merged),
        })
        return merged, report

    merged = val.copy()
    report["merged_rows"] = len(merged)
    return merged, report


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------
def style_axis(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(labelsize=7)


def draw_panel(
    ax: plt.Axes,
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    title: str,
    min_n: int,
) -> Dict[str, object]:
    if x_col not in df.columns:
        ax.text(0.5, 0.5, "Domain unavailable", ha="center", va="center", transform=ax.transAxes, fontsize=8)
        ax.set_title(title, fontsize=8)
        ax.axis("off")
        return {"status": "missing_column", "x_col": x_col, "n": 0, "r": np.nan, "p": np.nan}

    tmp = pd.DataFrame({
        "x": safe_numeric(df[x_col]),
        "y": safe_numeric(df[y_col]),
    }).replace([np.inf, -np.inf], np.nan).dropna()

    if len(tmp) < min_n or tmp["x"].nunique() < 2 or tmp["y"].nunique() < 2:
        ax.text(
            0.5, 0.5,
            f"Insufficient data\nn={len(tmp)}",
            ha="center", va="center", transform=ax.transAxes, fontsize=8,
        )
        ax.set_title(title, fontsize=8)
        ax.axis("off")
        return {"status": "insufficient", "x_col": x_col, "n": len(tmp), "r": np.nan, "p": np.nan}

    r, p = stats.pearsonr(tmp["x"], tmp["y"])
    slope, intercept, _, _, _ = stats.linregress(tmp["x"], tmp["y"])

    ax.scatter(tmp["x"], tmp["y"], s=12, alpha=0.65, linewidths=0)
    xs = np.linspace(tmp["x"].min(), tmp["x"].max(), 100)
    ax.plot(xs, intercept + slope * xs, lw=1.2)
    ax.axhline(0, lw=0.6, ls="--", alpha=0.5)
    ax.axvline(0, lw=0.6, ls="--", alpha=0.5)

    p_txt = "p<0.001" if p < 0.001 else f"p={p:.3g}"
    ax.set_title(f"{title}\nn={len(tmp)}, r={r:.2f}, {p_txt}", fontsize=8)
    ax.set_xlabel(DOMAIN_LABELS.get(x_col, x_col), fontsize=7)
    ax.set_ylabel("cBAG", fontsize=7)
    ax.grid(True, alpha=0.18)
    style_axis(ax)

    return {
        "status": "plotted",
        "x_col": x_col,
        "n": len(tmp),
        "r": float(r),
        "p": float(p),
        "slope": float(slope),
        "intercept": float(intercept),
    }


def make_domain_figure(
    merged_by_cohort: Dict[str, pd.DataFrame],
    cbag_by_cohort: Dict[str, str],
    feature_set: str,
    domains: Sequence[str],
    domain_type: str,
    outdir: Path,
    formats: Sequence[str],
    min_n: int,
) -> List[Dict[str, object]]:
    n_rows = len(COHORTS)
    n_cols = len(domains)

    fig_w = 3.0 * n_cols
    fig_h = 2.5 * n_rows
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(fig_w, fig_h), squeeze=False)

    stats_rows: List[Dict[str, object]] = []

    for i, cohort in enumerate(COHORTS):
        df = merged_by_cohort.get(cohort, pd.DataFrame())
        y_col = cbag_by_cohort.get(cohort, "")
        for j, domain in enumerate(domains):
            ax = axes[i, j]
            title = f"{cohort}: {DOMAIN_LABELS.get(domain, domain)}"
            if df.empty or not y_col:
                ax.text(0.5, 0.5, "No merged data", ha="center", va="center", transform=ax.transAxes, fontsize=8)
                ax.set_title(title, fontsize=8)
                ax.axis("off")
                row = {"status": "no_data", "x_col": domain, "n": 0, "r": np.nan, "p": np.nan}
            else:
                row = draw_panel(ax, df, domain, y_col, title, min_n=min_n)

            row.update({
                "feature_set": feature_set,
                "domain_type": domain_type,
                "cohort": cohort,
                "domain": domain,
                "cbag_col": y_col,
            })
            stats_rows.append(row)

    fig.suptitle(
        f"cBAG associations with harmonized cognitive domains ({feature_set}, {domain_type})",
        fontsize=13,
        y=0.995,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.975])

    stem = f"Figure_CognitiveDomains_{feature_set}_{domain_type}"
    for fmt in formats:
        path = outdir / f"{stem}.{fmt}"
        fig.savefig(path, dpi=300, bbox_inches="tight")
        print(f"[INFO] Saved {path}")
    plt.close(fig)

    return stats_rows


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------
def main() -> None:
    args = parse_args()
    base_dir = Path(args.base_dir)
    results_root = Path(args.results_root) if args.results_root else base_dir / "results"
    composite_dir = Path(args.composite_dir) if args.composite_dir else results_root / "composite_cognition"
    outdir = Path(args.outdir) if args.outdir else composite_dir / "cbag_domain_associations"
    outdir.mkdir(parents=True, exist_ok=True)

    print("BASE_DIR:", base_dir)
    print("RESULTS_ROOT:", results_root)
    print("COMPOSITE_DIR:", composite_dir)
    print("OUTDIR:", outdir)
    print("FEATURE_SETS:", ", ".join(args.feature_sets))
    print("COHORTS:", ", ".join(args.cohorts))

    all_stats: List[Dict[str, object]] = []
    merge_reports: List[Dict[str, object]] = []

    for feature_set in args.feature_sets:
        print(f"\n[INFO] Processing feature set: {feature_set}")
        merged_by_cohort: Dict[str, pd.DataFrame] = {}
        cbag_by_cohort: Dict[str, str] = {}

        for cohort in args.cohorts:
            val_path = validation_csv_path(results_root, cohort, feature_set)
            comp_path = composite_csv_path(composite_dir, cohort)

            if not val_path.exists():
                print(f"[WARN] Missing validation CSV: {val_path}")
                merge_reports.append({
                    "feature_set": feature_set,
                    "cohort": cohort,
                    "issue": "missing_validation_csv",
                    "validation_path": str(val_path),
                    "composite_path": str(comp_path),
                })
                continue
            if not comp_path.exists():
                print(f"[WARN] Missing composite CSV: {comp_path}")
                merge_reports.append({
                    "feature_set": feature_set,
                    "cohort": cohort,
                    "issue": "missing_composite_csv",
                    "validation_path": str(val_path),
                    "composite_path": str(comp_path),
                })
                continue

            val = pd.read_csv(val_path, low_memory=False)
            comp = pd.read_csv(comp_path, low_memory=False)

            cbag_col = first_existing(val, CBAG_PRIORITY)
            if cbag_col is None:
                print(f"[WARN] No cBAG column found for {cohort} {feature_set}")
                merge_reports.append({
                    "feature_set": feature_set,
                    "cohort": cohort,
                    "issue": "missing_cbag_col",
                    "validation_path": str(val_path),
                    "composite_path": str(comp_path),
                })
                continue

            merged, report = choose_best_merge(val, comp, cohort)
            report.update({
                "feature_set": feature_set,
                "validation_path": str(val_path),
                "composite_path": str(comp_path),
                "cbag_col": cbag_col,
            })
            merge_reports.append(report)
            merged_by_cohort[cohort] = merged
            cbag_by_cohort[cohort] = cbag_col

            merged_path = outdir / f"cbag_cognitive_domain_merged_{feature_set}_{cohort}.csv"
            merged.to_csv(merged_path, index=False)

            domain_counts = {d: int(merged[d].notna().sum()) if d in merged.columns else 0 for d in DOMAINS_RAW + DOMAINS_RESID}
            print(
                f"[INFO] {cohort} {feature_set}: merge={report['merge_strategy']} "
                f"overlap={report['overlap']} cBAG={cbag_col} domain_nonmissing={domain_counts}"
            )

        all_stats.extend(
            make_domain_figure(
                merged_by_cohort=merged_by_cohort,
                cbag_by_cohort=cbag_by_cohort,
                feature_set=feature_set,
                domains=DOMAINS_RAW,
                domain_type="raw",
                outdir=outdir,
                formats=args.formats,
                min_n=args.min_n,
            )
        )

        all_stats.extend(
            make_domain_figure(
                merged_by_cohort=merged_by_cohort,
                cbag_by_cohort=cbag_by_cohort,
                feature_set=feature_set,
                domains=DOMAINS_RESID,
                domain_type="resid",
                outdir=outdir,
                formats=args.formats,
                min_n=args.min_n,
            )
        )

    stats_df = pd.DataFrame(all_stats)
    merge_df = pd.DataFrame(merge_reports)

    stats_path = outdir / "cbag_cognitive_domain_stats.csv"
    merge_path = outdir / "cbag_cognitive_domain_merge_report.csv"
    stats_df.to_csv(stats_path, index=False)
    merge_df.to_csv(merge_path, index=False)

    print("\n[DONE]")
    print("Stats:", stats_path)
    print("Merge report:", merge_path)
    print("Figures/output dir:", outdir)


if __name__ == "__main__":
    main()
